IT_Task_Manager/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("authentication.urls", namespace="authentication")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("task_manager.urls", namespace="task-manager")),
]

authentication/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from authentication.views import register_view, login_view, ChangePasswordView

urlpatterns = [
    path("login/", login_view, name="login"),
    path("register/", register_view, name="sign-up"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("change-password/", ChangePasswordView.as_view(), name="password_change"),
]

app_name = "authentication"

task_manager/urls.py
from django.urls import path

from .views import (
    index,
    TaskListView,
    WorkerListView,
    TaskDetailView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskCreateView,
    MyCompletedTaskListView,
    MyInProgressTaskListView,
    complete_task,
    TaskTypeListView,
    TaskTypeUpdateView,
    TaskTypeCreateView,
    TaskTypeDeleteView,
    PositionListView,
    PositionDeleteView,
    PositionUpdateView,
    PositionCreateView,
    TaskDeleteView,
    TaskUpdateView,
    rick_roll,
)
urlpatterns = [
    path("", index, name="index"),
    path("rick_roll/", rick_roll, name="rick-roll"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path(
        "my_completed_tasks/",
        MyCompletedTaskListView.as_view(),
        name="my-completed-task-list",
    ),
    path(
        "my_in_progress_tasks/",
        MyInProgressTaskListView.as_view(),
        name="my-in-progress-task-list",
    ),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/complete", complete_task, name="toggle-task-complete"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("worker/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("worker/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("worker/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("task_types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task_type/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path("position/", PositionListView.as_view(), name="position-list"),
    path("position/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "position/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "position/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
]


app_name = "task-manager"

templates/includes/footer-auth.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
      <div class="container">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-12 col-md-6 my-auto">
            <div class="copyright text-center text-sm text-white text-lg-start">
              &copy; <a href="https://github.com/AnyoneClown" class="font-weight-bold text-white" target="_blank">Coded by AnyoneClown</a>
            </div>
          </div>
          <div class="col-12 col-md-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
              <li class="nav-item">
                <a href="{% url 'task-manager:rick-roll' %}" class="nav-link text-white" target="_blank">Sources</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'task-manager:rick-roll' %}" class="nav-link text-white" target="_blank">Support</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer.html
<footer class="footer py-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mb-4 mx-auto text-center">
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Company
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          About Us
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Team
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Products
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Blog
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Pricing
        </a>
      </div>
      <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
        <a href="{% url 'task-manager:rick-roll' %}" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-dribbble"></span>
        </a>
        <a href="{% url 'task-manager:rick-roll' %}" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-twitter"></span>
        </a>
        <a href="{% url 'task-manager:rick-roll' %}" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-instagram"></span>
        </a>
        <a href="{% url 'task-manager:rick-roll' %}" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-pinterest"></span>
        </a>
        <a href="https://github.com/AnyoneClown" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-github"></span>
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col-8 mx-auto text-center mt-1">
        <p class="mb-0 text-secondary">
          &copy; <a href="https://github.com/AnyoneClown" class="font-weight-bold" target="_blank">Coded by AnyoneClown</a>
        </p>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation-transparent.html
  <!-- Navbar Transparent -->
  <nav class="navbar navbar-expand-lg position-absolute top-0 z-index-3 w-100 shadow-none my-3  navbar-transparent ">
    <div class="container">
      <a class="navbar-brand  text-white " href="/" rel="tooltip" data-placement="bottom">
        IT Task Manager
      </a>
      <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon mt-2">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </span>
      </button>
      <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
        <ul class="navbar-nav navbar-nav-hover ms-auto">

          {% if request.user.is_authenticated %}

            <li class="nav-item dropdown dropdown-hover mx-2 ms-lg-6">
              <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" id="dropdownMenuPages8" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                Pages
                <img src="{{ ASSETS_ROOT }}/img/down-arrow-white.svg" alt="down-arrow" class="arrow ms-2 d-lg-block d-none">
                <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-2 d-lg-none d-block">
              </a>
              <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-lg mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages8">
                <div class="d-none d-lg-block">
                  <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                    Landing Pages
                  </h6>
                  <a href="/about-us.html" class="dropdown-item border-radius-md">
                    <span>About Us</span>
                  </a>
                  <a href="/contact-us.html" class="dropdown-item border-radius-md">
                    <span>Contact Us</span>
                  </a>
                  <a href="/author.html" class="dropdown-item border-radius-md">
                    <span>Author</span>
                  </a>
                  <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                    Account
                  </h6>
                  <a href="/sign-in.html" class="dropdown-item border-radius-md">
                    <span>Sign In</span>
                  </a>
                </div>
                <div class="d-lg-none">
                  <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                    Landing Pages
                  </h6>
                  <a href="/about-us.html" class="dropdown-item border-radius-md">
                    <span>About Us</span>
                  </a>
                  <a href="/contact-us.html" class="dropdown-item border-radius-md">
                    <span>Contact Us</span>
                  </a>
                  <a href="/author.html" class="dropdown-item border-radius-md">
                    <span>Author</span>
                  </a>
                  <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                    Account
                  </h6>
                  <a href="/sign-in.html" class="dropdown-item border-radius-md">
                    <span>Sign In</span>
                  </a>
                </div>
              </div>
            </li>

          {% endif %}

          {% if request.user.is_authenticated %}
              <li class="nav-item ms-lg-auto">
                <form action="{% url 'authentication:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="nav-link nav-link-icon me-2" style="background-color: transparent; border: none;">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</p>
                  </button>
                </form>
              </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->

templates/includes/navigation.html
  <!-- Navbar -->
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid px-0">
            <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip" data-placement="bottom">
              IT Task Manager
            </a>
            <a class="navbar-brand font-weight-bolder ms-sm-3" href="{{ user.get_absolute_url }}" rel="tooltip" data-placement="bottom">
              Active user: {{ user.username }}
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-auto">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                    Profile
                    <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                  </a>
                  <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                    <div class="d-none d-lg-block">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                        Account
                      </h6>
                      <a href="{{ user.get_absolute_url }}" class="dropdown-item border-radius-md">
                        <span>Profile</span>
                      </a>
                      <a href="{% url 'task-manager:my-completed-task-list' %}" class="dropdown-item border-radius-md">
                        <span>Completed tasks</span>
                      </a>
                      <a href="{% url 'task-manager:my-in-progress-task-list' %}" class="dropdown-item border-radius-md">
                        <span>In progress tasks</span>
                      </a>
                    </div>
                  </div>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuBlocks" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="material-icons opacity-6 me-2 text-md">view_day</i>
                  Sections
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end dropdown-menu-animation dropdown-md dropdown-md-responsive p-3 border-radius-lg mt-0 mt-lg-3" aria-labelledby="dropdownMenuBlocks">
                    <div class="d-none d-lg-block">
                      <li class="nav-item dropdown dropdown-hover dropdown-subitem">
                        <a class="dropdown-item py-2 ps-3 border-radius-md" href="/">
                          <div class="w-100 d-flex align-items-center justify-content-between">
                          <div>
                            <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Types and Positions</h6>
                            <span class="text-sm">See all</span>
                          </div>
                            <img src="{{ ASSETS_ROOT }}/img/down-arrow.svg" alt="down-arrow" class="arrow">
                          </div>
                        </a>
                        <div class="dropdown-menu mt-0 py-3 px-2 mt-3">
                          <a class="dropdown-item ps-3 border-radius-md mb-1" href="{% url 'task-manager:task-type-list' %}">
                            Task types list
                          </a>
                          <a class="dropdown-item ps-3 border-radius-md mb-1" href="{% url 'task-manager:task-type-create' %}">
                            Create task type
                          </a>
                          <a class="dropdown-item ps-3 border-radius-md mb-1" href="{% url 'task-manager:position-list' %}">
                            Position list
                          </a>
                          <a class="dropdown-item ps-3 border-radius-md mb-1" href="{% url 'task-manager:position-create' %}">
                            Create position
                          </a>
                        </div>
                      </li>
                      <li class="nav-item dropdown dropdown-hover dropdown-subitem">
                        <a class="dropdown-item py-2 ps-3 border-radius-md" href="/">
                          <div class="w-100 d-flex align-items-center justify-content-between">
                            <div>
                              <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Tasks</h6>
                              <span class="text-sm">All tasks</span>
                            </div>
                            <img src="{{ ASSETS_ROOT }}/img/down-arrow.svg" alt="down-arrow" class="arrow">
                          </div>
                        </a>
                        <div class="dropdown-menu mt-0 py-3 px-2 mt-3">
                          <a class="dropdown-item ps-3 border-radius-md mb-1" href="{% url 'task-manager:task-list' %}">
                            Tasks list
                          </a>
                          <a class="dropdown-item ps-3 border-radius-md mb-1" href="{% url 'task-manager:task-create' %}">
                            Create task
                          </a>
                        </div>
                      </li>
                      <li class="nav-item dropdown dropdown-hover dropdown-subitem">
                        <a class="dropdown-item py-2 ps-3 border-radius-md" href="/">
                          <div class="w-100 d-flex align-items-center justify-content-between">
                            <div>
                              <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Workers</h6>
                              <span class="text-sm">All workers</span>
                            </div>
                            <img src="{{ ASSETS_ROOT }}/img/down-arrow.svg" alt="down-arrow" class="arrow">
                          </div>
                        </a>
                        <div class="dropdown-menu mt-0 py-3 px-2 mt-3">
                          <a class="dropdown-item ps-3 border-radius-md mb-1" href="{% url 'task-manager:worker-list' %}">
                            Workers list
                          </a>
                        </div>
                      </li>
                    </div>
                  </ul>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item ms-lg-auto">
                      <form action="{% url 'authentication:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="nav-link nav-link-icon me-2" style="background-color: transparent; border: none;">
                          <i class="fa fa-sign-out me-1"></i>
                          <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</p>
                        </button>
                      </form>
                    </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
<section class="py-2">
  <div class="container">
    <div class="row">
      <div class="col-lg-2 mx-auto">
        <ul class="pagination pagination-lg">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link"><<</a>
            </li>
          {% endif %}
          <li class="page-item">
            <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
          </li>
          {% if page_obj.has_next %}
            <li class="page-item">
              <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">>></a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</section>
{% endif %}

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>