IT_Task_Manager/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("authentication.urls", namespace="authentication")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("task_manager.urls", namespace="task-manager")),
]

authentication/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from authentication.views import register_view, login_view, ChangePasswordView

urlpatterns = [
    path("login/", login_view, name="login"),
    path("register/", register_view, name="sign-up"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("change-password/", ChangePasswordView.as_view(), name="password_change"),
]

app_name = "authentication"

task_manager/urls.py
from django.urls import path

from .views import (
    index,
    TaskListView,
    WorkerListView,
    TaskDetailView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskCreateView,
    MyCompletedTaskListView,
    MyInProgressTaskListView,
    complete_task,
    TaskTypeListView,
    TaskTypeUpdateView,
    TaskTypeCreateView,
    TaskTypeDeleteView,
    PositionListView,
    PositionDeleteView,
    PositionUpdateView,
    PositionCreateView,
    TaskDeleteView,
    TaskUpdateView,
    rick_roll,
)
urlpatterns = [
    path("", index, name="index"),
    path("rick_roll/", rick_roll, name="rick-roll"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path(
        "my_completed_tasks/",
        MyCompletedTaskListView.as_view(),
        name="my-completed-task-list",
    ),
    path(
        "my_in_progress_tasks/",
        MyInProgressTaskListView.as_view(),
        name="my-in-progress-task-list",
    ),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/complete", complete_task, name="toggle-task-complete"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("worker/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("worker/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("worker/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("task_types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task_type/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path("position/", PositionListView.as_view(), name="position-list"),
    path("position/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "position/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "position/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
]


app_name = "task-manager"

task_manager/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Worker(AbstractUser):
    position = models.ForeignKey("Position", on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self) -> str:
        return f"Username: {self.username} FL: {self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("task-manager:worker-detail", kwargs={"pk": self.pk})


class Position(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    PRIORITY_CHOICES = (
        ("UR", "Urgent"),
        ("HG", "High"),
        ("MD", "Medium"),
        ("LW", "Low"),
    )

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField()
    priority = models.CharField(max_length=2, choices=PRIORITY_CHOICES, default="LW")
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(get_user_model(), related_name="tasks")

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("task-manager:task-detail", kwargs={"pk": self.pk})

    def get_priority_display(self) -> str:
        return dict(self.PRIORITY_CHOICES).get(self.priority, self.priority)

task_manager/forms.py
from django import forms
from django.contrib.auth import get_user_model

from task_manager.models import Position, Task, TaskType


class TaskForm(forms.ModelForm):
    PRIORITY_CHOICES = (
        ("UR", "Urgent"),
        ("HG", "High"),
        ("MD", "Medium"),
        ("LW", "Low"),
    )

    name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Name", "class": "form-control"})
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={"placeholder": "Description", "class": "form-control"}
        )
    )
    deadline = forms.DateTimeField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "type": "text",
                "placeholder": "Deadline",
                "id": "id_deadline",
            }
        ),
        input_formats=["%Y-%m-%d %H:%M:%S"],
    )

    priority = forms.ChoiceField(
        choices=PRIORITY_CHOICES,
        widget=forms.Select(attrs={"placeholder": "Priority", "class": "form-control"}),
    )
    task_type = forms.ModelChoiceField(
        queryset=TaskType.objects.all(),
        widget=forms.Select(
            attrs={"placeholder": "Task Type", "class": "form-control"}
        ),
    )
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.SelectMultiple(
            attrs={"placeholder": "Assignees", "class": "form-control"}
        ),
    )

    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "deadline",
            "priority",
            "task_type",
            "assignees",
        ]

    def save(self, commit=True):
        task = super(TaskForm, self).save(commit=False)
        task.is_completed = False
        if commit:
            task.save()
            self.save_m2m()
        return task


class TaskTypeForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Name", "class": "form-control"})
    )

    class Meta:
        model = TaskType
        fields = [
            "name",
        ]


class PositionForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Name", "class": "form-control"})
    )

    class Meta:
        model = Position
        fields = [
            "name",
        ]


class BaseSearchForm(forms.Form):
    search_query = forms.CharField(
        label=False,
        max_length=255,
        required=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name",
            }
        ),
    )


class WorkerSearchForm(forms.Form):
    search_query = forms.CharField(
        label=False,
        max_length=255,
        required=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by username",
            }
        ),
    )


class WorkerUpdateForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "Username", "class": "form-control"}
        )
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": "Email", "class": "form-control"})
    )
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "First name", "class": "form-control"}
        )
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "Last name", "class": "form-control"}
        )
    )
    position = forms.ModelChoiceField(
        queryset=Position.objects.all(),
        widget=forms.Select(
            attrs={"placeholder": "Last name", "class": "form-control"}
        ),
    )

    class Meta:
        model = get_user_model()
        fields = ("username", "email", "first_name", "last_name", "position")

task_manager/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic

from task_manager.models import Task, TaskType, Position, Worker
from task_manager.forms import (
    WorkerUpdateForm,
    TaskForm,
    TaskTypeForm,
    PositionForm,
    BaseSearchForm,
    WorkerSearchForm,
)


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_workers = get_user_model().objects.count()
    completed_tasks = Task.objects.filter(is_completed=True).count()
    num_tasks = Task.objects.count()

    context = {
        "num_workers": num_workers,
        "completed_tasks": completed_tasks,
        "num_tasks": num_tasks,
    }
    return render(request, "task_manager/index.html", context=context)


class BaseSearchListView(generic.ListView):
    """
    A base class for Django list views with integrated search functionality.

    Subclasses can inherit from this base class to easily add search capabilities
    to list views. It provides pagination, context object name, and search form handling.

    Attributes:
        paginate_by (int): Number of items per page for pagination.
        context_object_name (str): Variable to use in the template for the list of objects.
        search_form_class (Form): Form class responsible for handling search queries.
        queryset (QuerySet): The base queryset for the list view.
        search_field (str): The field to use for searching.
    """

    paginate_by = 5
    context_object_name = "object_list"
    search_form_class = None
    queryset = None
    search_field = "name"

    def get_queryset(self):
        form = self.search_form_class(self.request.GET)

        if form.is_valid():
            self.queryset = self.queryset.filter(
                **{f"{self.search_field}__icontains": form.cleaned_data["search_query"]}
            )
        return self.queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = self.search_form_class(
            initial={"search_query": self.request.GET.get("search_query", "")}
        )
        return context


class TaskListView(LoginRequiredMixin, BaseSearchListView):
    model = Task
    template_name = "task_manager/task/task_list.html"
    queryset = Task.objects.select_related("task_type").prefetch_related("assignees")
    search_form_class = BaseSearchForm
    search_field = "name"


class MyCompletedTaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 5
    context_object_name = "task_list"
    template_name = "task_manager/task/my_completed_task_list.html"

    def get_queryset(self):
        return Task.objects.filter(
            assignees=self.request.user, is_completed=True
        ).prefetch_related("assignees")


class MyInProgressTaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 5
    context_object_name = "task_list"
    template_name = "task_manager/task/my_in_progress_task_list.html"

    def get_queryset(self):
        return Task.objects.filter(
            assignees=self.request.user, is_completed=False
        ).prefetch_related("assignees")


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    template_name = "task_manager/task/task_detail.html"
    queryset = (
        Task.objects.all().select_related("task_type").prefetch_related("assignees")
    )

    def get_context_data(self, **kwargs):
        context = super(TaskDetailView, self).get_context_data(**kwargs)
        context["assignees"] = ", ".join(
            assignee.username for assignee in self.object.assignees.all()
        )
        return context


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    template_name = "task_manager/task/task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("task-manager:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    template_name = "task_manager/task/task_confirm_delete.html"
    success_url = reverse_lazy("task-manager:task-list")

    def dispatch(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs["pk"])
        if request.user not in task.assignees.all():
            return render(request, "task_manager/page-403.html")
        return super(TaskDeleteView, self).dispatch(request, *args, **kwargs)


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    template_name = "task_manager/task/task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("task-manager:task-list")

    def dispatch(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs["pk"])
        if request.user not in task.assignees.all():
            return render(request, "task_manager/page-403.html")
        return super(TaskUpdateView, self).dispatch(request, *args, **kwargs)


class WorkerListView(LoginRequiredMixin, BaseSearchListView):
    model = Worker
    template_name = "task_manager/worker/worker_list.html"
    queryset = Worker.objects.all()
    search_form_class = WorkerSearchForm
    search_field = "username"


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()
    template_name = "task_manager/worker/worker_detail.html"


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    template_name = "task_manager/worker/worker_form.html"
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("task-manager:worker-list")

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if user.is_authenticated and user.id != int(kwargs["pk"]):
            return render(request, "task_manager/page-403.html")
        return super(WorkerUpdateView, self).dispatch(request, *args, **kwargs)


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = get_user_model()
    template_name = "task_manager/worker/worker_confirm_delete.html"
    success_url = reverse_lazy("authentication:sign-up")

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if user.is_authenticated and user.id != int(kwargs["pk"]):
            return render(request, "task_manager/page-403.html")
        return super(WorkerDeleteView, self).dispatch(request, *args, **kwargs)


class TaskTypeListView(LoginRequiredMixin, BaseSearchListView):
    model = TaskType
    template_name = "task_manager/task_type/task_type_list.html"
    queryset = TaskType.objects.filter()
    search_form_class = BaseSearchForm


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    template_name = "task_manager/task_type/task_type_form.html"
    form_class = TaskTypeForm
    success_url = reverse_lazy("task-manager:task-type-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("task-manager:task-type-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    form_class = TaskTypeForm
    template_name = "task_manager/task_type/task_type_form.html"
    success_url = reverse_lazy("task-manager:task-type-list")


class PositionListView(LoginRequiredMixin, BaseSearchListView):
    model = Position
    template_name = "task_manager/position/position_list.html"
    queryset = Position.objects.all()
    search_form_class = BaseSearchForm


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    form_class = PositionForm
    template_name = "task_manager/position/position_form.html"
    success_url = reverse_lazy("task-manager:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    template_name = "task_manager/position/position_confirm_delete.html"
    success_url = reverse_lazy("task-manager:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    form_class = PositionForm
    template_name = "task_manager/position/position_form.html"
    success_url = reverse_lazy("task-manager:position-list")


@login_required
def complete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)

    if task.is_completed:
        task.is_completed = False
    else:
        task.is_completed = True
    task.save()
    return redirect(reverse_lazy("task-manager:task-detail", args=[pk]))


def rick_roll(request):
    return render(request, "task_manager/rick_roll.html")

templates/task_manager/my_task_list.html
{% extends "layouts/base.html" %}

{% block title %} Template Page {% endblock %}

{% block body_class %} index-page {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <div class="page-header min-vh-80" style="background-image: url('https://images.unsplash.com/photo-1630752708689-02c8636b9141?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2490&q=80')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <div class="text-center">
            <h1 class="text-white">My tasks</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
    <div class="container">
      <div class="section text-center">
        <h2 class="title">Task list</h2>
        {% if task_list %}
          <table class="table">
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Deadline</th>
              <th>Priority</th>
              <th>Task type</th>
              <th>Completed</th>
            </tr>

            {% for task in task_list %}
              <tr>
                <td>
                  {{ task.id }}
                </td>
                <td class="text-bold">
                  <a href="{{ task.get_absolute_url}}">{{ task.name }}</a>
                </td>
                <td>
                  {{ task.deadline }}
                </td>
                <td>
                  {{ task.get_priority_display }}
                </td>
                <td>
                  {{ task.task_type }}
                </td>
                <td>
                  {{ task.is_completed }}
                </td>
              </tr>
            {% endfor %}
            </table>

          {% else %}
              <p>You don't have any tasks yet.</p>
          {% endif %}
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/task_manager/rick_roll.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Sign IN {% endblock %}

{% block body_class %} sign-in-basic {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation-transparent.html' %}

  <div class="page-header align-items-start min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');" loading="lazy">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container my-auto">
      <div class="row">
        <video width="100%" height="550" autoplay muted>
          <source src="https://shattereddisk.github.io/rickroll/rickroll.mp4" type="video/mp4">
        </video>
      </div>
    </div>

    {% include 'includes/footer-auth.html' %}

  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascript %}{% endblock javascript %}

templates/task_manager/task_detail.html
{% extends "layouts/base.html" %}

{% block title %} Template Page {% endblock %}

{% block body_class %} index-page {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <div class="page-header min-vh-80" style="background-image: url('https://images.unsplash.com/photo-1630752708689-02c8636b9141?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2490&q=80')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <div class="text-center">
            <h1 class="text-white">Description:</h1>
            <span class="text-white">{{ task.description }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
    <div class="container">
      <div class="section text-center">
        <h2 class="title">Task info</h2>
        <table class="table">
          <tr>
            <th>ID</th>
            <th>Deadline</th>
            <th>Priority</th>
            <th>Task type</th>
            <th>Assignees</th>
            <th>Completed</th>
            {% if user in task.assignees.all %}
              {% if task.is_completed %}
                <th>Reopen task</th>
              {% else %}
                <th>Complete task</th>
              {% endif %}
            {% endif %}
          </tr>
            <tr>
              <td>
                {{ task.id }}
              </td>
              <td>
                {{ task.deadline }}
              </td>
              <td>
                {{ task.get_priority_display }}
              </td>
              <td>
                {{ task.task_type }}
              </td>
              <td>
                {{ assignees }}
              </td>
              <td>
                {% if task.is_completed %}
                  Completed
                {% else %}
                  In progress...
                {% endif %}
              </td>
              <td>
                {% if user in task.assignees.all %}
                  {% if task.is_completed %}
                    <button type="button" onclick="window.location.href='{% url 'task-manager:toggle-task-complete' pk=task.id %}'" class="btn bg-gradient-primary btn-sm">Reopen</button>
                  {% else %}
                    <button type="button" onclick="window.location.href='{% url 'task-manager:toggle-task-complete' pk=task.id %}'" class="btn bg-gradient-primary btn-sm">Complete</button>
                  {% endif %}
                {% endif %}
              </td>
            </tr>
          </table>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/task_manager/tasktype_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block title %} Template Page {% endblock %}

{% block body_class %} index-page {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <div class="page-header min-vh-80" style="background-image: url('https://images.unsplash.com/photo-1630752708689-02c8636b9141?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2490&q=80')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <div class="text-center">
            <h1 class="text-white">Task types</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
    <div class="container">
      <div class="section text-center">
        <form method="get" action="" class="form-inline">
          <div class="input-group input-group-outline mb-3">
            {{ search_form.search_query|as_crispy_field }}
            <input class="btn btn-secondary" type="submit" value="🔎">
          </div>
        </form>
        {% if object_list %}
          <table class="table">
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Update</th>
              <th>Delete</th>
            </tr>

            {% for task_type in object_list %}
              <tr>
                <td>
                  {{ task_type.id }}
                </td>
                <td>
                  {{ task_type.name }}
                </td>
                <td>
                  <button type="button" onclick="window.location.href='{% url 'task-manager:task-type-update' pk=task_type.id %}'" class="btn bg-gradient-secondary btn-sm">Update</button>
                </td>
                <td>
                  <button type="button" onclick="window.location.href='{% url 'task-manager:task-type-delete' pk=task_type.id %}'" class="btn bg-gradient-primary btn-sm">Delete</button>
                </td>
              </tr>
            {% endfor %}
            </table>

          {% else %}
              <p>There are no task types yet.</p>
          {% endif %}
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/task_manager/worker_detail.html
{% extends "layouts/base.html" %}

{% block title %} Template Page {% endblock %}

{% block body_class %} index-page {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <div class="page-header min-vh-80" style="background-image: url('https://images.unsplash.com/photo-1630752708689-02c8636b9141?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2490&q=80')">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <div class="text-center">
            <h1 class="text-white">Worker: {{ worker.username }}</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
    <div class="container">
      <div class="section text-center">
        <h2 class="title">Worker info</h2>
        <table class="table">
          <tr>
            <th>ID</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
            <th>Position</th>
            {% if user.id == worker.id %}
              <th>Update</th>
              <th>Change password</th>
              <th>Delete</th>
            {% endif %}
          </tr>
            <tr>
              <td>
                {{ worker.id }}
              </td>
              <td>
                {{ worker.first_name }}
              </td>
              <td>
                {{ worker.last_name }}
              </td>
              <td>
                {{ worker.email }}
              </td>
              <td>
                {{ worker.position }}
              </td>
              {% if user.id == worker.id %}
                <td>
                  <button type="button" onclick="window.location.href='{% url 'task-manager:worker-update' pk=worker.id %}'" class="btn bg-gradient-secondary btn-sm">Update</button>
                </td>
                <td>
                  <button type="button" onclick="window.location.href='{% url 'authentication:password_change' %}'" class="btn bg-gradient-secondary btn-sm">Change password</button>
                </td>
                <td>
                  <button type="button" onclick="window.location.href='{% url 'task-manager:worker-delete' pk=worker.id %}'" class="btn bg-gradient-primary btn-sm">Delete</button>
                </td>
              {% endif %}
          </tr>
        </table>
        <div class="text-center">
            <button type="button" onclick="window.location.href='{% url 'task-manager:worker-list' %}'" class="btn btn-lg bg-gradient-faded-white btn-lg w-100 mt-4 mb-0">Back</button>
          </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}